
pipeline {
 environment {

        registry = "bouguerra03/pfe"

        registryCredential = 'dockerhub_id'

        dockerImage = ''

    }
    agent any

    stages {
        stage('Checkout GIT') {
            steps {
                echo 'Pulling'
               git branch: 'main', credentialsId: 'oussama', url: 'https://github.com/oussamabouguerra/shamashit.git'

            }
        }
        stage('Maven Clean'){
            steps {
                bat 'mvn clean'
            }}
         stage('Maven Version'){
            steps {
                bat 'mvn -version'
            }
        }

        stage('Compile'){
            steps {
                bat 'mvn compile -e'
            }
        }

      
           stage('JUNIT/MOCKITO')
       {
         steps{
         bat 'mvn test -Dtest="com.youtube.jwt.service.ServiceBordereauTest.java"'

         }
       }
stage('sonar')
       {
         steps{
         bat 'mvn sonar:sonar \
  -Dsonar.projectKey=oussama \
  -Dsonar.host.url=http://192.168.1.22:9000 \
  -Dsonar.login=squ_e4fde6bf5e3a4b5c1b515a3b212f544c1acada89'
         }
       }
     stage('Nexus') {
  
    steps {
        bat "mvn deploy -DskipTests"
    }
}

       stage('Building our image') {

            steps {

                script {

                    dockerImage = docker.build registry + ":$BUILD_NUMBER"

                }

            }

        }

        stage('Deploy our image') {

            steps {

                script {

                    docker.withRegistry( '', registryCredential ) {

                        dockerImage.push()

                    }

                }

            }

        }

        stage('Cleaning up') {

            steps {

                bat "docker rmi $registry:$BUILD_NUMBER"

            }

        }

        stage('Docker Compose'){

        steps {

        bat "docker-compose up -d"

        }

        }

    }
}